version: '3.8'

services:
  # 1. フロントエンド（HTML/CSS）
  frontend:
    image: my-profile
    ports:
      - "8083:80"

  # 2. バックエンド（FastAPI）
  backend:
    build: . # Dockerfileがある場所を指定
    image: my-api
    ports:
      - "8001:8000"
    environment:
      # FastAPIに「データベースの場所とパスワード」を教える設定
      - DATABASE_URL=postgresql://myuser:mypassword@db:5433/mydb
    env_file:
      - .env # ここで.envファイルを読み込む
    depends_on:
      - db # データベースが立ち上がってからFastAPIを動かすというルール

  # 3. データベース（今回新しく追加！）
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data # コンテナを消してもデータを残すための「金庫」

# データを保存しておく金庫の場所を定義
volumes:
  db_data: